block-beta
    columns 7
    Source space:2 Sub space:2 Sink
    Source-- "input" -->Sub
    Sub-- "output" -->Sink

    classDef block height:48px,padding:8px;
    classDef hidden visibility:none;
    class Sub block
    class Source hidden
    class Sink hidden
