block-beta
    columns 7
    Source space:2 Batch space:2 Sink
    Source-- "input" -->Batch
    Batch-- "output" -->Sink

    classDef block height:48px,padding:8px;
    classDef hidden visibility:none;
    class Batch block
    class Source hidden
    class Sink hidden
