block-beta
    columns 7
    space:5 Sink1 space:1
    space:1 Source space:1 Replicate space:3
    space:5 Sink2 space:1
        
    Source-- "input" -->Replicate
    Replicate-- "output" -->Sink1
    Replicate-- "output" -->Sink2

    classDef block height:48px,padding:8px;
    classDef hidden visibility:none;
    class Replicate block
    class Source1 hidden
    class Source2 hidden
    class Sink1 hidden
    class Sink2 hidden
