sequenceDiagram
    autonumber
    participant BlockA as Another block (input source)
    participant Buffer.input as Buffer.input port
    participant Buffer as Buffer block
    participant Buffer.output as Buffer.output port
    participant BlockB as Another block (downstream sink)
    participant Buffer.trigger as Buffer.trigger port
    participant BlockC as Another block (trigger source)

    BlockA-->>Buffer: Connect (input)
    BlockC-->>Buffer: Connect (trigger)
    Buffer-->>BlockB: Connect (output)

    loop Storing messages
        BlockA->>Buffer: Message
        Buffer->>Buffer: Store message internally
    end

    BlockC->>Buffer: Trigger
    loop Releasing messages
        Buffer->>BlockB: Stored Message
    end

    BlockA-->>Buffer: Disconnect (input)
    Buffer-->>Buffer.input: Close

    BlockC-->>Buffer: Disconnect (trigger)
    Buffer-->>Buffer.trigger: Close

    Buffer-->>BlockB: Disconnect (output)
    Buffer-->>Buffer.output: Close
