sequenceDiagram
    autonumber
    participant Clock as Clock block
    participant Clock.output as Clock.output port
    participant BlockA as Another block

    Clock-->>BlockA: Connect

    Clock->>BlockA: Message

    Clock-->>Clock.output: Close
    Clock-->>BlockA: Disconnect
