sequenceDiagram
    autonumber
    participant BlockA as Another block
    participant Mapper.input as Mapper.input port
    participant Mapper as Mapper block
    participant Mapper.output as Mapper.output port
    participant BlockB as Another block

    BlockA-->>Mapper: Connect
    Mapper-->>BlockB: Connect

    loop Mapper process
        BlockA->>Mapper: Message
        Mapper->>Mapper: Transform
        Mapper->>BlockB: Message
    end

    BlockA-->>Mapper: Disconnect
    Mapper-->>Mapper.input: Close
    Mapper-->>Mapper.output: Close
    Mapper-->>BlockB: Disconnect
