# See: https://docs.github.com/en/actions/writing-workflows
---
name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0
          components: rustfmt
      - name: Check formatting
        run: cargo +1.80.0 fmt --all -- --check 2>/dev/null
  review-pr:
    name: Review PR
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - check-formatting
    permissions:
      pull-requests: write
    steps:
      - name: Approve PR
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              ...context.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
            });
      - name: Request changes
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              ...context.repo,
              pull_number: context.issue.number,
              event: 'REQUEST_CHANGES',
              body: 'TBD',
            });
