# See: https://docs.github.com/en/actions/writing-workflows
---
name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0
          components: rustfmt
      - name: Check formatting
        run: cargo +1.80.0 fmt --all -- --check 2>/dev/null
  check-targets:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            target: x86_64-unknown-linux-gnu
          - name: MacOS
            target: x86_64-apple-darwin
          - name: Windows
            target: x86_64-pc-windows-gnu
    name: Check ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.80.0
          targets: ${{ matrix.target }}
      - name: Check formatting
        id: formatting
        run: cargo +1.80.0-${{ matrix.target }} fmt --all -- --check 2>/dev/null
      - name: Check binaries
        id: bins
        run: cargo +1.80.0-${{ matrix.target }} check --workspace --bins
      - name: Check tests
        id: tests
        run: cargo +1.80.0-${{ matrix.target }} check --workspace --tests
      - name: Check examples
        id: examples
        run: cargo +1.80.0-${{ matrix.target }} check --workspace --examples
  review-pr:
    name: Review PR
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - check-formatting
      - check-targets
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            if (${{ needs.check-formatting.result == 'success' }}) {
              await github.rest.pulls.createReview({
                ...context.repo,
                pull_number: context.issue.number,
                event: 'APPROVE',
              });
            } else {
              await github.rest.pulls.createReview({
                ...context.repo,
                pull_number: context.issue.number,
                event: 'REQUEST_CHANGES',
                body: 'TBD',
              });
            }
