name: Release

# TODO:
# - Support signing macos binaries.

# Trigger on any tag creation.
on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-zigbuild: false # no reason to use zigbuild when building for host
            strip: true
            artifact: linux-x64
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   use-zigbuild: true
          #   strip: false
          #   artifact: linux-arm64
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          #   use-zigbuild: true
          #   strip: true
          #   artifact: macos-x64
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          #   use-zigbuild: true
          #   strip: false
          #   artifact: macos-arm64
          # - os: windows-latest
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            use-zigbuild: false # zigbuild doesn't support Windows
            strip: false
            artifact: windows-x64.exe
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            use-zigbuild: false
            strip: false
            artifact: windows2-x64.exe
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        uses: AsimovPlatform/build-rust-action@master
        with:
          target: ${{ matrix.target }}
          artifact-name: ${{ matrix.artifact }}
          strip: ${{ matrix.strip || 'false' }}
          use-zigbuild: ${{ matrix.use-zigbuild || 'false' }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Download artifacts
        uses: AsimovPlatform/release-action@master
        with:
          changelog_path: CHANGES.md
